[package]
name = "digitrek"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"
bevy_pkv = "0.15.0"
rand = "0.9.2"
serde = "1.0.228"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
open = "5.3.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.85", features = ["Window"] }
getrandom = { version = "0.3.4", features = ["wasm_js"] }

[features]
invincible = []
show_local_points = []
one_key = []
max_dif = []
min_delay = []
